foundation_stereo_node:
  ros__parameters:
    left_topic: /camera/left/image_rect
    right_topic: /camera/right/image_rect
    pointcloud_topic: /stereo/points
    depth_topic: /stereo/depth

    backend: tensorrt
    input_source: ros
    zmq_host: ${ZT_DRONE_IP}
    zmq_port: 5555
    zmq_rcv_hwm: 2
    zmq_poll_period_sec: 0.001
    output_frame_id: camera_left
    model_name: 23-36-37
    models_root: /home/kqu/capstone/foundation_stereo_ros/models
    trt_input_height: 0
    trt_input_width: 0

    intrinsic_file: /home/kqu/capstone/foundation_stereo_ros/K.txt
    device: cuda
    scale: 1.0
    input_height: 400
    input_width: 488

    valid_iters: 8  # pytorch uses this for inference; tensorrt uses it to select <model_name>_iter<valid_iters>
    max_disp: 192
    hiera: 0
    get_pc: 1
    remove_invisible: 1
    denoise_cloud: 0
    denoise_nb_points: 10
    denoise_radius: 0.03
    denoise_voxel_size: 0.01
    zfar: 5.0
    sync_slop: 0.03
    queue_size: 8
    log_every_n_frames: 10
