foundation_stereo_node:
  ros__parameters:
    left_topic: /camera/fisheye1/image_raw/rectified
    right_topic: /camera/fisheye2/image_raw/rectified
    pointcloud_topic: /stereo/points

    backend: tensorrt
    model_dir: /home/kqu/capstone/foundation_stereo_ros/models/torch/23-36-37/model_best_bp2_serialize.pth
    trt_engine_dir: /home/kqu/capstone/foundation_stereo_ros/models/trt/onnx_23-36-37_iter8/
    trt_cfg_file: ''
    trt_input_height: 0
    trt_input_width: 0

    intrinsic_file: /home/kqu/capstone/foundation_stereo_ros/K.txt
    device: cuda
    scale: 1.0
    input_height: 400
    input_width: 488

    valid_iters: 8
    max_disp: 192
    hiera: 0
    remove_invisible: 1
    zfar: 5.0
    sync_slop: 0.03
    queue_size: 8
